[project]
name = "sandr0-xyz"
version = "0.1.0"
description = "Personal Website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "mistune>=3.1.4",
    "pillow>=11.3.0",
    "pygments>=2.19.2",
]
